<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../IEmployeeMediator.wsdl"/>
      <rootElement name="processEmployee" namespace="http://enrichment.spring.soa.whitehorses.nl/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../WriteFile.wsdl"/>
      <rootElement name="Response" namespace="http://www.whitehorses.nl/spring"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.3.0(build 100415.2045.2557) AT [MON JUN 14 00:04:40 CEST 2010]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:tns="http://enrichment.spring.soa.whitehorses.nl/"
                xmlns:bpel2="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/file/SoaSpringEnrichment/SoaSpring/WriteFile"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns1="http://enrichment.spring.soa.whitehorses.nl/types"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:imp1="http://www.whitehorses.nl/spring"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns soap12 soap wsdl mime ns1 xsd plt ns0 imp1 xp20 bpws bpel2 bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <imp1:Response>
      <imp1:Employee>
        <imp1:Department>
          <imp1:Id>
            <xsl:value-of select="/tns:processEmployee/arg0/department/departmentId"/>
          </imp1:Id>
          <imp1:Name>
            <xsl:value-of select="/tns:processEmployee/arg0/department/name"/>
          </imp1:Name>
        </imp1:Department>
        <imp1:Id>
          <xsl:value-of select="/tns:processEmployee/arg0/employeeId"/>
        </imp1:Id>
        <imp1:FirstName>
          <xsl:value-of select="/tns:processEmployee/arg0/firstName"/>
        </imp1:FirstName>
        <imp1:LastName>
          <xsl:value-of select="/tns:processEmployee/arg0/lastName"/>
        </imp1:LastName>
        <imp1:State>
          <xsl:value-of select="/tns:processEmployee/arg0/state"/>
        </imp1:State>
      </imp1:Employee>
    </imp1:Response>
  </xsl:template>
</xsl:stylesheet>
