package nl.amis.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import nl.amis.types.ObjectFactory;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://virtual:6001/Kerberos-KerberosHelloWS-context-root/HelloServicePort?WSDL",
  targetNamespace="http://ws.kerberos.owsm.amis.nl/", name="HelloService")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface HelloService
{
  @WebMethod
  @Action(input="http://ws.kerberos.owsm.amis.nl/HelloService/sayHelloRequest",
    output="http://ws.kerberos.owsm.amis.nl/HelloService/sayHelloResponse")
  @ResponseWrapper(localName="sayHelloResponse", targetNamespace="http://ws.kerberos.owsm.amis.nl/",
    className="nl.amis.types.SayHelloResponse")
  @RequestWrapper(localName="sayHello", targetNamespace="http://ws.kerberos.owsm.amis.nl/",
    className="nl.amis.types.SayHello")
  @WebResult(targetNamespace="")
  public String sayHello(@WebParam(targetNamespace="", name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);
}
