<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../frontReference.wsdl"/>
      <rootElement name="EmployeesCollection" namespace="http://www.amis.nl/front/ebo"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../frontService.wsdl"/>
      <rootElement name="EmployeesCollection" namespace="http://www.amis.nl/front/ebo"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.4.0(build 110106.1932.5682) AT [FRI NOV 18 23:22:31 CET 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ebo="http://www.amis.nl/front/ebo"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://www.amis.nl/frontReference"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns0="http://www.amis.nl/front"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl xsi ebo wsoap12 soapenc soap mime wsdl tns xsd http ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ebo:EmployeesCollection>
      <xsl:for-each select="/ebo:EmployeesCollection/ebo:Employees">
        <ebo:Employees>
          <ebo:employeeId>
            <xsl:value-of select="ebo:employeeId"/>
          </ebo:employeeId>
          <xsl:if test="ebo:firstName">
            <ebo:firstName>
              <xsl:if test="ebo:firstName/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ebo:firstName/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ebo:firstName"/>
            </ebo:firstName>
          </xsl:if>
          <xsl:if test="ebo:lastName">
            <ebo:lastName>
              <xsl:value-of select="ebo:lastName"/>
            </ebo:lastName>
          </xsl:if>
          <xsl:if test="ebo:email">
            <ebo:email>
              <xsl:value-of select="ebo:email"/>
            </ebo:email>
          </xsl:if>
          <xsl:if test="ebo:phoneNumber">
            <ebo:phoneNumber>
              <xsl:if test="ebo:phoneNumber/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ebo:phoneNumber/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ebo:phoneNumber"/>
            </ebo:phoneNumber>
          </xsl:if>
          <xsl:if test="ebo:hireDate">
            <ebo:hireDate>
              <xsl:value-of select="ebo:hireDate"/>
            </ebo:hireDate>
          </xsl:if>
          <xsl:if test="ebo:jobId">
            <ebo:jobId>
              <xsl:value-of select="ebo:jobId"/>
            </ebo:jobId>
          </xsl:if>
          <xsl:if test="ebo:salary">
            <ebo:salary>
              <xsl:if test="ebo:salary/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ebo:salary/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ebo:salary"/>
            </ebo:salary>
          </xsl:if>
          <xsl:if test="ebo:commissionPct">
            <ebo:commissionPct>
              <xsl:if test="ebo:commissionPct/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ebo:commissionPct/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ebo:commissionPct"/>
            </ebo:commissionPct>
          </xsl:if>
          <xsl:if test="ebo:managerId">
            <ebo:managerId>
              <xsl:if test="ebo:managerId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ebo:managerId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ebo:managerId"/>
            </ebo:managerId>
          </xsl:if>
          <xsl:if test="ebo:departmentId">
            <ebo:departmentId>
              <xsl:if test="ebo:departmentId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="ebo:departmentId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ebo:departmentId"/>
            </ebo:departmentId>
          </xsl:if>
        </ebo:Employees>
      </xsl:for-each>
    </ebo:EmployeesCollection>
  </xsl:template>
</xsl:stylesheet>
