package nl.amis.ws.client;

import javax.xml.ws.WebFault;

import nl.amis.ws.types.FaultType;

@WebFault(faultBean="nl.amis.ws.types.FaultType", targetNamespace="http://www.customfaults.org",
  name="BusinessFault")
public class BusinessFaultMessage
  extends Exception
{
  private FaultType faultInfo;

  public BusinessFaultMessage(String message, FaultType faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public BusinessFaultMessage(String message, FaultType faultInfo,
                              Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public FaultType getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(FaultType faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)
