package nl.amis.ws.client;

import javax.xml.rpc.soap.SOAPFaultException;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceRef;

import nl.amis.ws.types.Departments;
import nl.amis.ws.types.InputDepartmentType;
import nl.amis.ws.types.ObjectFactory;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

public class Front_ptClient
{
  @WebServiceRef
  private static FrontMediator_ep frontMediator_ep;

  public static void main(String [] args)
  {
    frontMediator_ep = new FrontMediator_ep();
    Front_ptt front_ptt = frontMediator_ep.getFront_pt();
    // Add your code to call the desired methods.
    ObjectFactory obj = new ObjectFactory();
    InputDepartmentType input = obj.createInputDepartmentType();
    input.setDepartmentId(101);
    try {
        Departments dep = front_ptt.validateDepartment(input);
        System.out.println("Department =" + dep.getDepartmentId());
    } catch (BusinessFaultMessage e) {
        System.out.println("got a business fault");
        System.out.println(e.getFaultInfo().getFaultCode());
        System.out.println(e.getFaultInfo().getFaultDesciption());
    } catch (SOAPFaultException e) {
        System.out.println("got soap fault");
        e.printStackTrace();
    } catch (WebServiceException e) {
        System.out.println("got web service fault");
        e.printStackTrace();
    }
  }
}
