package nl.amis.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

import nl.amis.ws.types.Departments;
import nl.amis.ws.types.DepartmentsCollection;
import nl.amis.ws.types.EmployeesCollection;
import nl.amis.ws.types.InputDepartmentType;
import nl.amis.ws.types.InputParametersType;
import nl.amis.ws.types.ObjectFactory;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://SOAPS3.alfa.local:8001/soa-infra/services/default/Front/Front?WSDL",
  targetNamespace="http://www.amis.nl/front", name="front_ptt")
@XmlSeeAlso(
  { ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface Front_ptt
{
  @WebMethod(operationName="GetAllDepartments", action="GetAllDepartments")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="GetAllDepartments", output="http://www.amis.nl/front/front_ptt/GetAllDepartmentsResponse")
  @WebResult(targetNamespace="http://www.amis.nl/front/ebo", partName="Departments",
    name="DepartmentsCollection")
  public DepartmentsCollection getAllDepartments(@WebParam(targetNamespace="http://www.amis.nl/front/ebo",
      partName="Parameters", name="InputParameters")
    InputParametersType Parameters);

  @WebMethod(operationName="GetAllEmployees", action="GetAllEmployees")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="GetAllEmployees", output="http://www.amis.nl/front/front_ptt/GetAllEmployeesResponse")
  @WebResult(targetNamespace="http://www.amis.nl/front/ebo", partName="Employees",
    name="EmployeesCollection")
  public EmployeesCollection getAllEmployees(@WebParam(targetNamespace="http://www.amis.nl/front/ebo",
      partName="Parameters", name="InputParameters")
    InputParametersType Parameters);

  @WebMethod(operationName="ValidateDepartment", action="ValidateDepartment")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="ValidateDepartment", fault =
      { @FaultAction(value="http://www.amis.nl/front/front_ptt/ValidateDepartment/Fault/BusinessFault",
          className = BusinessFaultMessage.class) }, output="http://www.amis.nl/front/front_ptt/ValidateDepartmentResponse")
  @WebResult(targetNamespace="http://www.amis.nl/front/ebo", partName="Department",
    name="Department")
  public Departments validateDepartment(@WebParam(targetNamespace="http://www.amis.nl/front/ebo",
      partName="Parameters", name="InputDepartment")
    InputDepartmentType Parameters)
    throws BusinessFaultMessage;
}
