package nl.amis.ws.client;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://SOAPS3.alfa.local:8001/soa-infra/services/default/Front/Front?WSDL",
  targetNamespace="http://www.amis.nl/front", name="FrontMediator_ep")
public class FrontMediator_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("nl.amis.ws.client.FrontMediator_ep");
      URL baseUrl = FrontMediator_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            FrontMediator_ep.class.getResource("http://SOAPS3.alfa.local:8001/soa-infra/services/default/Front/Front?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://SOAPS3.alfa.local:8001/soa-infra/services/default/Front/Front?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://SOAPS3.alfa.local:8001/soa-infra/services/default/Front/Front?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://SOAPS3.alfa.local:8001/soa-infra/services/default/Front/Front?WSDL",
          e);
    }
  }

  public FrontMediator_ep()
  {
    super(wsdlLocationURL,
          new QName("http://www.amis.nl/front", "FrontMediator_ep"));
  }

  public FrontMediator_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="front_pt")
  public Front_ptt getFront_pt()
  {
    return (Front_ptt) super.getPort(new QName("http://www.amis.nl/front",
                                               "front_pt"),
                                     Front_ptt.class);
  }

  @WebEndpoint(name="front_pt")
  public Front_ptt getFront_pt(WebServiceFeature... features)
  {
    return (Front_ptt) super.getPort(new QName("http://www.amis.nl/front",
                                               "front_pt"),
                                     Front_ptt.class, features);
  }
}
