<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../HrDepartment.wsdl"/>
      <rootElement name="DepartmentsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/HrDepartment"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../source.wsdl"/>
      <rootElement name="Department" namespace="http://www.amis.nl/source/ebo"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.4.0(build 110106.1932.5682) AT [FRI NOV 18 23:35:24 CET 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns0="http://www.amis.nl/source"
                xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ebo="http://www.amis.nl/source/ebo"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAdecouple/Source/HrDepartment"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/HrDepartment"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl tns xsd top xsi ns0 wsoap12 soapenc soap mime ebo http xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ebo:Department>
      <ebo:departmentId>
        <xsl:value-of select="/top:DepartmentsCollection/top:Departments/top:departmentId"/>
      </ebo:departmentId>
      <xsl:if test="/top:DepartmentsCollection/top:Departments/top:departmentName">
        <ebo:departmentName>
          <xsl:value-of select="/top:DepartmentsCollection/top:Departments/top:departmentName"/>
        </ebo:departmentName>
      </xsl:if>
      <xsl:if test="/top:DepartmentsCollection/top:Departments/top:managerId">
        <ebo:managerId>
          <xsl:if test="/top:DepartmentsCollection/top:Departments/top:managerId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/top:DepartmentsCollection/top:Departments/top:managerId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/top:DepartmentsCollection/top:Departments/top:managerId"/>
        </ebo:managerId>
      </xsl:if>
      <xsl:if test="/top:DepartmentsCollection/top:Departments/top:locationId">
        <ebo:locationId>
          <xsl:if test="/top:DepartmentsCollection/top:Departments/top:locationId/@xsi:nil">
            <xsl:attribute name="xsi:nil">
              <xsl:value-of select="/top:DepartmentsCollection/top:Departments/top:locationId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/top:DepartmentsCollection/top:Departments/top:locationId"/>
        </ebo:locationId>
      </xsl:if>
    </ebo:Department>
  </xsl:template>
</xsl:stylesheet>
