<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../HrEmployees.wsdl"/>
      <rootElement name="EmployeesCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/HrEmployees"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../source.wsdl"/>
      <rootElement name="EmployeesCollection" namespace="http://www.amis.nl/source/ebo"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.4.0(build 110106.1932.5682) AT [FRI NOV 18 22:59:08 CET 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns0="http://www.amis.nl/source"
                xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ebo="http://www.amis.nl/source/ebo"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/HrEmployees"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAdecouple/Source/HrEmployees"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl top xsd tns xsi ns0 wsoap12 soapenc soap mime ebo http xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ebo:EmployeesCollection>
      <xsl:for-each select="/top:EmployeesCollection/top:Employees">
        <ebo:Employees>
          <ebo:employeeId>
            <xsl:value-of select="top:employeeId"/>
          </ebo:employeeId>
          <xsl:if test="top:firstName">
            <ebo:firstName>
              <xsl:if test="top:firstName/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="top:firstName/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="top:firstName"/>
            </ebo:firstName>
          </xsl:if>
          <xsl:if test="top:lastName">
            <ebo:lastName>
              <xsl:value-of select="top:lastName"/>
            </ebo:lastName>
          </xsl:if>
          <xsl:if test="top:email">
            <ebo:email>
              <xsl:value-of select="top:email"/>
            </ebo:email>
          </xsl:if>
          <xsl:if test="top:phoneNumber">
            <ebo:phoneNumber>
              <xsl:if test="top:phoneNumber/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="top:phoneNumber/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="top:phoneNumber"/>
            </ebo:phoneNumber>
          </xsl:if>
          <xsl:if test="top:hireDate">
            <ebo:hireDate>
              <xsl:value-of select="top:hireDate"/>
            </ebo:hireDate>
          </xsl:if>
          <xsl:if test="top:jobId">
            <ebo:jobId>
              <xsl:value-of select="top:jobId"/>
            </ebo:jobId>
          </xsl:if>
          <xsl:if test="top:salary">
            <ebo:salary>
              <xsl:if test="top:salary/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="top:salary/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="top:salary"/>
            </ebo:salary>
          </xsl:if>
          <xsl:if test="top:commissionPct">
            <ebo:commissionPct>
              <xsl:if test="top:commissionPct/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="top:commissionPct/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="top:commissionPct"/>
            </ebo:commissionPct>
          </xsl:if>
          <xsl:if test="top:managerId">
            <ebo:managerId>
              <xsl:if test="top:managerId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="top:managerId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="top:managerId"/>
            </ebo:managerId>
          </xsl:if>
          <xsl:if test="top:departmentId">
            <ebo:departmentId>
              <xsl:if test="top:departmentId/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="top:departmentId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="top:departmentId"/>
            </ebo:departmentId>
          </xsl:if>
        </ebo:Employees>
      </xsl:for-each>
    </ebo:EmployeesCollection>
  </xsl:template>
</xsl:stylesheet>
