package osb.cookbook.owsm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://localhost:7001/01_Securing-an-OSB-service/proxy/Customer?WSDL",
  targetNamespace="http://osb-cookbook/CustomerManagement", name="CustomerManagement")
@XmlSeeAlso(
  { osb.cookbook.owsm.types.ObjectFactory.class })
public interface CustomerManagement
{
  @WebMethod(operationName="FindCustomer", action="http://osb-cookbook/CustomerManagement/FindCustomer")
  @Action(input="http://osb-cookbook/CustomerManagement/FindCustomer",
    output="http://osb-cookbook/CustomerManagement/CustomerManagement/FindCustomerResponse")
  @ResponseWrapper(localName="FindCustomerResponse", targetNamespace="http://osb-cookbook/CustomerManagement",
    className="osb.cookbook.owsm.types.FindCustomerResponse")
  @RequestWrapper(localName="FindCustomer", targetNamespace="http://osb-cookbook/CustomerManagement",
    className="osb.cookbook.owsm.types.FindCustomer")
  @WebResult(targetNamespace="", name="Customer")
  public osb.cookbook.owsm.types.CustomerTyp findCustomer(@WebParam(targetNamespace="",
      name="ID")
    long id);
}
