package osb.cookbook.owsm.client;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://localhost:7001/01_Securing-an-OSB-service/proxy/Customer?WSDL",
  targetNamespace="http://osb-cookbook/CustomerManagement", name="CustomerManagementSOAPQSService")
public class CustomerManagementSOAPQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("osb.cookbook.owsm.client.CustomerManagementSOAPQSService");
      URL baseUrl = CustomerManagementSOAPQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            CustomerManagementSOAPQSService.class.getResource("http://localhost:7001/01_Securing-an-OSB-service/proxy/Customer?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:7001/01_Securing-an-OSB-service/proxy/Customer?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://localhost:7001/01_Securing-an-OSB-service/proxy/Customer?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:7001/01_Securing-an-OSB-service/proxy/Customer?WSDL",
          e);
    }
  }

  public CustomerManagementSOAPQSService()
  {
    super(wsdlLocationURL,
          new QName("http://osb-cookbook/CustomerManagement",
                    "CustomerManagementSOAPQSService"));
  }

  public CustomerManagementSOAPQSService(URL wsdlLocation,
                                         QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="CustomerManagementSOAPQSPort")
  public osb.cookbook.owsm.client.CustomerManagement getCustomerManagementSOAPQSPort()
  {
    return (osb.cookbook.owsm.client.CustomerManagement) super.getPort(new QName("http://osb-cookbook/CustomerManagement",
                                                                                 "CustomerManagementSOAPQSPort"),
                                                                       osb.cookbook.owsm.client.CustomerManagement.class);
  }

  @WebEndpoint(name="CustomerManagementSOAPQSPort")
  public osb.cookbook.owsm.client.CustomerManagement getCustomerManagementSOAPQSPort(WebServiceFeature... features)
  {
    return (osb.cookbook.owsm.client.CustomerManagement) super.getPort(new QName("http://osb-cookbook/CustomerManagement",
                                                                                 "CustomerManagementSOAPQSPort"),
                                                                       osb.cookbook.owsm.client.CustomerManagement.class,
                                                                       features);
  }
}
