package writefile.soaspring.soaspringenrichment.file.adapter.pcbpel.com.oracle.xmlns;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

@WebService(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/SoaSpringEnrichment/SoaSpring/WriteFile",
  name="Write_ptt")
@XmlSeeAlso(
  { writefile.soaspring.soaspringenrichment.file.adapter.pcbpel.com.oracle.xmlns.ObjectFactory.class })
public interface Write_ptt
{
  @WebMethod(operationName="Write")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/pcbpel/adapter/file/SoaSpringEnrichment/SoaSpring/WriteFile/Write_ptt/Write")
  @Oneway
  public void write(@WebParam(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/",
      partName="opaque", name="opaqueElement")
    byte[] opaque);
}
