<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ReceiveEmployeeEmail.wsdl"/>
      <rootElement name="message" namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/ReceiveEmployeeEmail"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../SendEmployeeResponse.wsdl"/>
      <rootElement name="message" namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/SendEmployeeResponse"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [SUN MAY 13 19:59:11 CEST 2012]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ums/UmsSOA/IncomingEmail/ReceiveEmployeeEmail"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/ums/UmsSOA/IncomingEmail/SendEmployeeResponse"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://b2b/Employee"
                xmlns:ns2="http://platform.integration.oracle/blocks/adapter/fw/metadata/SendEmployeeResponse"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns3="http://b2b/Employee/response"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:imp1="http://platform.integration.oracle/blocks/adapter/fw/metadata/ReceiveEmployeeEmail"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns pc plt wsdl ns0 jca xsd imp1 ns1 ns2 ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns2:message>
      <ns3:message>
        <ns3:header>
          <ns3:type>
            <xsl:value-of select="/imp1:message/ns0:message/ns0:header/ns0:type"/>
          </ns3:type>
          <ns3:agreementId>
            <xsl:value-of select="/imp1:message/ns0:message/ns0:header/ns0:id"/>
          </ns3:agreementId>
          <ns3:sender>
            <xsl:value-of select="/imp1:message/ns0:message/ns0:header/ns0:sender"/>
          </ns3:sender>
          <ns3:receiver>
            <xsl:value-of select="/imp1:message/ns0:message/ns0:header/ns0:receiver"/>
          </ns3:receiver>
          <ns3:id>
            <xsl:value-of select="/imp1:message/ns0:message/ns0:header/ns0:id"/>
          </ns3:id>
        </ns3:header>
        <ns3:result>
          <ns3:employeeId>
            <xsl:value-of select="/imp1:message/ns0:message/ns0:employee/ns0:employeeId"/>
          </ns3:employeeId>
          <ns3:status>
            <xsl:text disable-output-escaping="no">success</xsl:text>
          </ns3:status>
        </ns3:result>
      </ns3:message>
    </ns2:message>
  </xsl:template>
</xsl:stylesheet>
