<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Mediator"
     targetNamespace="http://xmlns.oracle.com/SoaSpringEnrichment/SoaSpring/Mediator"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://www.whitehorses.nl/spring"
     xmlns:tns="http://xmlns.oracle.com/SoaSpringEnrichment/SoaSpring/Mediator"
     xmlns:out1="http://www.whitehorses.nl/spring"
    >
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.whitehorses.nl/spring" schemaLocation="SCA-INF/classes/xsd/EmployeeEnrichment.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.whitehorses.nl/spring" schemaLocation="SCA-INF/classes/xsd/EmployeeEnrichment.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:Request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="reply" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
