package nl.amis.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://virtual:8001/soa-infra/services/default/SAMLHello/HelloMediator_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Test/Hello/HelloMediator",
  name="execute_ptt")
@XmlSeeAlso(
  { nl.amis.client.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface Execute_ptt
{
  @WebMethod(action="execute")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="execute", output="http://xmlns.oracle.com/Test/Hello/HelloMediator/execute_ptt/executeResponse")
  @WebResult(targetNamespace="http://www.amis.nl/greetings", partName="reply",
    name="response")
  public nl.amis.client.types.Response execute(@WebParam(targetNamespace="http://www.amis.nl/greetings",
      partName="request", name="sayHello")
    nl.amis.client.types.SayHello request);
}
