package nl.amis.client.service;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.WebServiceRef;

import nl.amis.client.types.ObjectFactory;
import nl.amis.client.types.Response;
import nl.amis.client.types.SayHello;

import weblogic.wsee.jws.jaxws.owsm.SecurityPoliciesFeature;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

public class Execute_ptClient
{
  @WebServiceRef
  private static HelloMediator_ep helloMediator_ep;

  public static void main(String [] args) throws MalformedURLException {
    
    URL wsdl = new URL("http://virtual:8001/soa-infra/services/default/SAMLHello/HelloMediator_ep?WSDL");
    QName qname = new QName("http://xmlns.oracle.com/Test/Hello/HelloMediator",
                    "HelloMediator_ep");
    
    helloMediator_ep = new HelloMediator_ep(wsdl,qname);

    SecurityPoliciesFeature securityFeatures =
            new SecurityPoliciesFeature(new String[] { "oracle/wss_username_token_client_policy" });
    Execute_ptt execute_ptt = helloMediator_ep.getExecute_pt(securityFeatures);
        // Add your code to call the desired methods.
    Map<String, Object> reqContext = ((BindingProvider)  execute_ptt).getRequestContext();  
    // Add the user
    reqContext.put(BindingProvider.USERNAME_PROPERTY, "client" );
    reqContext.put(BindingProvider.PASSWORD_PROPERTY, "weblogic1" );

    ObjectFactory obj = new ObjectFactory();
    SayHello request = obj.createSayHello();
    request.setName("edwin");
    request.setMessage("Hi");
    Response response = execute_ptt.execute(request);
    System.out.println(response.getMessage());
    
  }
}
