package nl.amis.client.service;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://virtual:8001/soa-infra/services/default/SAMLHello/HelloMediator_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Test/Hello/HelloMediator",
  name="HelloMediator_ep")
public class HelloMediator_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("nl.amis.client.service.HelloMediator_ep");
      URL baseUrl = HelloMediator_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            HelloMediator_ep.class.getResource("http://virtual:8001/soa-infra/services/default/SAMLHello/HelloMediator_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://virtual:8001/soa-infra/services/default/SAMLHello/HelloMediator_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://virtual:8001/soa-infra/services/default/SAMLHello/HelloMediator_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://virtual:8001/soa-infra/services/default/SAMLHello/HelloMediator_ep?WSDL",
          e);
    }
  }

  public HelloMediator_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/Test/Hello/HelloMediator",
                    "HelloMediator_ep"));
  }

  public HelloMediator_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="execute_pt")
  public nl.amis.client.service.Execute_ptt getExecute_pt()
  {
    return (nl.amis.client.service.Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/Test/Hello/HelloMediator",
                                                                        "execute_pt"),
                                                              nl.amis.client.service.Execute_ptt.class);
  }

  @WebEndpoint(name="execute_pt")
  public nl.amis.client.service.Execute_ptt getExecute_pt(WebServiceFeature... features)
  {
    return (nl.amis.client.service.Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/Test/Hello/HelloMediator",
                                                                        "execute_pt"),
                                                              nl.amis.client.service.Execute_ptt.class,
                                                              features);
  }
}
